name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: debian-11.1
            platforms: linux/386, linux/amd64, linux/ppc64le
          - tag: debian-10.1
            platforms: linux/386, linux/amd64, linux/ppc64le
          - tag: debian-10.2
            platforms: linux/386, linux/amd64, linux/ppc64le
          - tag: debian-9.11
            platforms: linux/386, linux/amd64
          - tag: ubuntu-18.04
            platforms: linux/386, linux/amd64, linux/ppc64le
          - tag: ubuntu-20.04
            platforms: linux/amd64, linux/ppc64le
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platforms }}
          build-args: BASE_IMAGE=pizzafactory0contorno/piatto:${{ matrix.tag }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/gcc-aarch64-linux-gnu:${{ matrix.tag }}
